const assert=require('node:assert/strict');const {load,el,PAGE_ERRORS,b64e}=require('./dom');const opened=[];
function open(hash){const w=load('tarot',hash).window;w.matchMedia=()=>({matches:true});opened.push(w);return w;}
const hash=url=>url.slice(url.indexOf('#'));
try{
 const a=open();assert.equal(a.TAROT_DECK.length,22);assert.equal(new Set(a.TAROT_DECK.map(c=>c[0])).size,22);el(a,'makerName').value='지민';a.document.querySelector('[data-topic="2"]').click();el(a,'begin').click();assert.equal(a.document.querySelectorAll('[data-pick]').length,3);a.document.querySelector('[data-pick="1"]').click();assert.equal(el(a,'sealed').hidden,false);assert.equal(el(a,'readings').children.length,0);
 const invite=a.psyShareData();assert.ok(invite.url.includes('#c='));assert.ok(invite.desc.includes('서로에게 필요한 것'));assert.ok(invite.url.length<1500);a.dispatchEvent(new a.HashChangeEvent('hashchange'));assert.equal(el(a,'sealed').hidden,false);
 const b=open(hash(invite.url));assert.equal(el(b,'invitation').hidden,false);assert.equal(el(b,'readings').children.length,0);el(b,'guestName').value='민수';el(b,'join').click();b.document.querySelector('[data-pick="2"]').click();assert.equal(el(b,'outcome').hidden,false);assert.equal(el(b,'readings').children.length,3);const names=[...b.document.querySelectorAll('.tarot-face h2')].map(e=>e.textContent);assert.equal(new Set(names).size,3);const result=b.psyShareData();assert.ok(result.url.includes('#r='));
 const r=open(hash(result.url));assert.equal(el(r,'readings').textContent,el(b,'readings').textContent);assert.equal(el(r,'mission').textContent,el(b,'mission').textContent);b.history.replaceState(null,'',hash(invite.url));b.dispatchEvent(new b.HashChangeEvent('hashchange'));assert.equal(el(b,'outcome').hidden,false);el(b,'again').click();assert.equal(el(b,'intro').hidden,false);assert.equal(el(b,'readings').children.length,0);
 const c=JSON.parse(Buffer.from(hash(invite.url).slice(3),'base64url').toString());for(let i=0;i<22;i++){const rotated={...c,d:Array.from({length:22},(_,j)=>(i+j)%22),i:0};const w=open('#r='+b64e(JSON.stringify({c:rotated,n:'너',i:1})));assert.equal(w.document.querySelector('.tarot-face h2').textContent,a.TAROT_DECK[i][0]);assert.equal(w.document.querySelectorAll('.tarot-reading').length,3);assert.ok(el(w,'mission').textContent);}
 for(const invalid of [{...c,d:Array(22).fill(0)},{...c,t:3},{...c,i:3},{...c,v:9},{...c,id:'bad'}])assert.equal(el(open('#c='+b64e(JSON.stringify(invalid))),'invalid').hidden,false);
 for(const bad of ['#c=bad','#r='+b64e(JSON.stringify({c,n:'x',i:9})),'#c='+'a'.repeat(2000)])assert.equal(el(open(bad),'invalid').hidden,false);
 const safe=open('#c='+b64e(JSON.stringify({...c,n:'<img src=x>'})));assert.equal(el(safe,'inviteName').children.length,0);assert.equal(el(safe,'inviteName').textContent,'<img src=x>');
 opened.forEach(w=>w.close());assert.deepEqual(PAGE_ERRORS,[]);console.log('타로 검사 통과: 봉인·초대·결과 답장, 3장 중복 없음, 22장 해석, 동일 링크 고정, 잘못된 데이터·이름 안전 표시');
}catch(e){opened.forEach(w=>w.close());throw e;}
