const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const E=require('../assets/tarot-engine');const {load,el,PAGE_ERRORS,b64e}=require('./dom');const opened=[];
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/tarot-deck.js'),'utf8'),sandbox);const {TAROT_DECK:D,TAROT_DETAILS:M,TAROT_PATTERNS:P}=sandbox.window;
function open(hash){const w=load('tarot',hash).window;opened.push(w);return w;}
const hash=url=>url.slice(url.indexOf('#')), encoded=(type,data)=>'#'+type+'='+b64e(JSON.stringify(data));
function pick(w,i){w.document.querySelector('[data-pick="'+i+'"]').click();assert.equal(el(w,'draw').hidden,false);el(w,'confirmPick').click();}
function flip(w){for(let i=0;i<3;i++)w.document.querySelector('[data-reveal="'+i+'"]').click();}
try{
 assert.equal(D.length,22);assert.equal(M.length,22);assert.equal(new Set(M.map(d=>d[0])).size,22);assert.equal(P.length,3);P.forEach(p=>assert.equal(Object.keys(p).length,6));M.forEach(d=>{assert.equal(d[1].length,2);assert.ok(d[3].length>35);assert.equal((d[4].match(/\?/g)||[]).length,2);});
 const snapshots=[0,1,20260910,4294967295].map(s=>{const c={v:2,s,t:0,a:10,n:'나'},cards=E.cards(c,11);return {s,aLayout:E.layout(s,'a'),bLayout:E.layout(s,'b'),...cards,pattern:E.pattern(cards.a,cards.b,M)};});assert.deepEqual(snapshots,JSON.parse(fs.readFileSync(path.join(__dirname,'tarot-golden.json'),'utf8')));
 for(let a=0;a<22;a++)for(let b=0;b<22;b++){const cards=E.cards({v:2,s:20260910,t:0,a,n:'나'},b);assert.notEqual(cards.us,cards.a);assert.notEqual(cards.us,cards.b);assert.equal(E.pattern(cards.a,cards.b,M),E.pattern(cards.b,cards.a,M));}
 const a=open();el(a,'makerName').value='지민';a.document.querySelector('[data-topic="2"]').click();el(a,'begin').click();assert.equal(a.document.querySelectorAll('[data-pick]').length,22);assert.equal(el(a,'confirmPick').disabled,true);pick(a,10);assert.equal(el(a,'sealed').hidden,false);assert.equal(el(a,'preview').querySelectorAll('.tarot-face').length,1);assert.equal(el(a,'preview').textContent.includes(M[0][3]),false);const invite=a.psyShareData();assert.ok(invite.url.length<650);a.dispatchEvent(new a.HashChangeEvent('hashchange'));assert.equal(el(a,'sealed').hidden,false);
 const c=JSON.parse(Buffer.from(hash(invite.url).slice(3),'base64url').toString());const b=open(hash(invite.url));el(b,'guestName').value='민수';el(b,'join').click();const sameIndex=E.layout(c.s,'b').indexOf(E.layout(c.s,'a')[c.a]);pick(b,sameIndex);assert.equal(el(b,'outcome').hidden,false);assert.equal(el(b,'shareControls').hidden,true);assert.equal(b.document.querySelector('[data-reveal="1"]').disabled,true);b.document.querySelector('[data-reveal="0"]').click();assert.equal(el(b,'pairSection').hidden,true);b.document.querySelector('[data-reveal="1"]').click();assert.equal(el(b,'pairSection').hidden,false);assert.equal(el(b,'sameBadge').hidden,false);b.document.querySelector('[data-reveal="2"]').click();assert.equal(el(b,'conversation').hidden,false);assert.equal(el(b,'shareControls').hidden,false);const result=b.psyShareData();const r=open(hash(result.url));assert.equal(el(r,'perspective').hidden,false);el(r,'viewA').click();flip(r);assert.equal(el(r,'pairName').textContent,el(b,'pairName').textContent);assert.equal(el(r,'questionText').textContent,el(b,'questionText').textContent);assert.ok(el(r,'readings').textContent.includes('나의 카드 · 지민'));
 a.history.replaceState(null,'',hash(result.url));a.dispatchEvent(new a.HashChangeEvent('hashchange'));assert.equal(el(a,'outcome').hidden,false);assert.equal(el(a,'conversation').hidden,true);assert.ok(el(a,'readings').textContent.includes('나의 카드 · 지민'));flip(a);el(b,'newTopic').click();assert.equal(el(b,'intro').hidden,false);assert.equal(el(b,'readings').children.length,0);
 const legacy={v:1,id:'cd9a41211f20587d',t:2,n:'먼저 보낸 친구',d:[6,1,15,9,10,21,11,12,19,13,20,2,4,8,14,16,3,18,0,7,5,17],i:1};const old=open(encoded('c',legacy));el(old,'join').click();assert.equal(old.document.querySelectorAll('[data-pick]').length,3);pick(old,2);flip(old);assert.deepEqual(E.cards(legacy,2),{a:1,b:9,us:10});
 for(const invalid of [{...c,s:-1},{...c,s:1.5},{...c,a:22},{...c,t:3},{...c,v:9},{...legacy,d:Array(22).fill(0)}])assert.equal(el(open(encoded('c',invalid)),'invalid').hidden,false);
 for(const bad of ['#c=bad',encoded('r',{c,n:'x',b:22}),'#c='+'a'.repeat(2000)])assert.equal(el(open(bad),'invalid').hidden,false);
 const safe=open(encoded('c',{...c,n:'<img src=x>'}));assert.equal(el(safe,'inviteName').children.length,0);assert.equal(el(safe,'inviteName').textContent,'<img src=x>');assert.deepEqual(PAGE_ERRORS,[]);
 console.log('Tarot v2 passed: golden layouts, 484 pairs, same card, half seal, 3 manual reveals, perspectives, legacy links, validation and safe names.');
}finally{opened.forEach(w=>w.close());}
