(function(){
 'use strict';
 const R=window.OmokRules,$=id=>document.getElementById(id),params=new URLSearchParams(location.search);
 let state=R.create(),mode=['local','online'].includes(params.get('mode'))?params.get('mode'):'ai',level='steady',human=1,pending=-1,focusIndex=112,busy=false,timer=null,epoch=0;
 let online=null;
 const board=$('board'),points=[],coord=i=>String.fromCharCode(65+i%15)+(Math.floor(i/15)+1),name=color=>mode==='local'?(color===1?'흑돌':'백돌'):(color===human?'나':'컴퓨터');
 const done=()=>!!(state.winner||state.draw),canPlay=()=>!$('game').hidden&&!busy&&!done()&&(mode==='online'?online&&online.canPlay():mode==='local'||state.turn===human);
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 600 600');svg.classList.add('om-grid-lines');svg.setAttribute('aria-hidden','true');
 for(let n=0;n<15;n++){for(const vertical of [false,true]){const line=document.createElementNS(svg.namespaceURI,'line');line.setAttribute('x1',vertical?20+n*40:20);line.setAttribute('y1',vertical?20:20+n*40);line.setAttribute('x2',vertical?20+n*40:580);line.setAttribute('y2',vertical?580:20+n*40);line.setAttribute('stroke','#b39167');line.setAttribute('stroke-width','1.4');svg.append(line);}}
 for(const [r,c] of [[3,3],[3,11],[7,7],[11,3],[11,11]]){const circle=document.createElementNS(svg.namespaceURI,'circle');circle.setAttribute('cx',20+c*40);circle.setAttribute('cy',20+r*40);circle.setAttribute('r','4');circle.setAttribute('fill','#b39167');svg.append(circle);}board.append(svg);
 for(let r=0;r<15;r++){const row=document.createElement('div');row.className='om-grid-row';row.setAttribute('role','row');row.setAttribute('aria-rowindex',r+1);for(let c=0;c<15;c++){const i=r*15+c,b=document.createElement('button');b.type='button';b.className='om-point';b.dataset.index=i;b.dataset.stone='0';b.setAttribute('role','gridcell');b.setAttribute('aria-colindex',c+1);b.setAttribute('aria-label',coord(i)+' 빈자리');b.tabIndex=i===112?0:-1;row.append(b);points.push(b);}board.append(row);}
 function cancelBot(){epoch++;if(timer!==null)clearTimeout(timer);timer=null;busy=false;}
 function undoCount(){if(!state.moves.length)return 0;if(mode==='local')return 1;for(let i=state.moves.length-1;i>=0;i--)if(state.moves[i].color===human)return state.moves.length-i;return 0;}
 function lobby(){cancelBot();if(online)online.leave();$('replay').disabled=false;pending=-1;$('game').hidden=true;$('lobby').hidden=false;document.body.classList.remove('playing');syncOptions();}
 function syncOptions(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));document.querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.level===level)));document.querySelectorAll('[data-color]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.color===human)));$('aiOptions').hidden=mode!=='ai';$('modeNote').textContent=mode==='online'?'카톡 초대 링크를 열면 각자 휴대폰에서 둘 수 있어요.':mode==='local'?'한 기기를 번갈아 보며 둬요. 흑돌을 맡을 사람부터 정해봐요.':'컴퓨터와 번갈아 둬요. 흑돌이 먼저 시작해요.';$('backLink').textContent=mode!=='ai'?'← 다른 둘이놀기':'← 다른 혼자놀기';$('backLink').href=mode!=='ai'?'../../?home=play#all':'../../?tab=solo#all';document.querySelectorAll('.om-nav a').forEach((a,i)=>{a.removeAttribute('aria-current');if(i===(mode!=='ai'?0:1))a.setAttribute('aria-current','page');});if(online)online.render();}
 function render(){const finished=done(),last=state.moves[state.moves.length-1];
  points.forEach((b,i)=>{b.dataset.stone=state.board[i];b.classList.toggle('last',!!last&&last.index===i);b.classList.toggle('pending',pending===i);b.classList.toggle('winning',state.line.includes(i));b.setAttribute('aria-label',coord(i)+' '+(state.board[i]===1?'흑돌':state.board[i]===2?'백돌':pending===i?'선택한 빈자리':'빈자리')+(last&&last.index===i?' · 마지막 수':''));b.setAttribute('aria-selected',String(pending===i));b.setAttribute('aria-disabled',String(!canPlay()||!!state.board[i]));b.tabIndex=i===focusIndex?0:-1;});
  $('blackSeat').classList.toggle('active',!finished&&state.turn===1);$('whiteSeat').classList.toggle('active',!finished&&state.turn===2);$('blackName').textContent=name(1);$('whiteName').textContent=name(2);$('modeLabel').textContent=mode==='local'?'한 화면에서 둘이':'컴퓨터와 · '+(level==='easy'?'가볍게':'생각하며');
  $('turnStatus').textContent=finished?(state.draw?'빈자리가 없어요. 무승부!':name(state.winner)+' 승리!'):busy?'컴퓨터가 다음 수를 생각하고 있어요':mode==='local'?name(state.turn)+' 차례예요. 자리를 골라봐요.':'내 차례예요. 어디에 둘까요?';
  $('moveCount').textContent=state.moves.length+'수';$('lastMove').textContent=last?'마지막 수 · '+coord(last.index)+' '+(last.color===1?'흑돌':'백돌'):'흑돌부터 시작해요';
  $('selectedPoint').textContent=pending<0?'판에서 자리를 골라주세요':coord(pending)+' · '+(Math.floor(pending/15)+1)+'행 '+(pending%15+1)+'열';
  $('place').disabled=!canPlay()||pending<0||!!state.board[pending];$('place').textContent=busy?'컴퓨터가 두는 중…':pending<0?'자리를 고른 뒤 여기에 두기':coord(pending)+' · 여기에 두기';
  document.querySelectorAll('[data-nudge]').forEach(b=>b.disabled=!canPlay());$('undo').disabled=!undoCount();$('undo').textContent=mode==='ai'?'내 차례로 무르기':'한 수 무르기';$('placement').hidden=finished;$('result').hidden=!finished;
  if(finished){$('resultTitle').textContent=state.draw?'빈틈없이 잘 막았어!':mode==='ai'?(state.winner===human?'다섯 알, 내가 이겼다!':'이번 한판은 컴퓨터 승리!'):name(state.winner)+'이 먼저 이었어요!';$('resultNote').textContent=state.draw?'225곳을 모두 채웠어요. 이번에는 무승부예요.':state.moves.length+'수 만에 승부가 났어요. 테두리로 표시한 돌들이 이어졌어요.';}
  if(online)online.render();
 }
 function scheduleBot(){if(mode!=='ai'||done()||state.turn===human)return;busy=true;pending=-1;render();const ticket=epoch;timer=setTimeout(()=>{timer=null;if(ticket!==epoch||$('game').hidden)return;const index=R.chooseMove(state.board,state.turn,level);if(index>=0)R.play(state,index);busy=false;render();},320);}
 function start(){if(mode==='online'){online.start();return;}cancelBot();$('replay').disabled=false;state=R.create();pending=-1;focusIndex=112;$('lobby').hidden=true;$('game').hidden=false;document.body.classList.add('playing');render();scheduleBot();window.scrollTo({top:0,behavior:'auto'});}
 function select(i){if(!canPlay())return;if(state.board[i]){$('turnStatus').textContent='이미 돌이 있는 자리예요. 빈자리를 골라주세요.';return;}pending=i;focusIndex=i;render();}
 function moveSelection(dr,dc,keyboard=false){if(!canPlay())return;const from=pending>=0?pending:focusIndex,r=Math.max(0,Math.min(14,Math.floor(from/15)+dr)),c=Math.max(0,Math.min(14,from%15+dc));focusIndex=r*15+c;pending=state.board[focusIndex]?-1:focusIndex;render();if(state.board[focusIndex])$('selectedPoint').textContent=coord(focusIndex)+' · 이미 돌이 있어요';if(keyboard)points[focusIndex].focus({preventScroll:true});}
 board.addEventListener('click',e=>{const b=e.target.closest('[data-index]');if(b)select(+b.dataset.index);});
 board.addEventListener('keydown',e=>{const delta={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]}[e.key];if(!delta)return;e.preventDefault();const b=e.target.closest('[data-index]');if(b)focusIndex=+b.dataset.index;moveSelection(...delta,true);});
 document.querySelectorAll('[data-nudge]').forEach(b=>b.addEventListener('click',()=>{const d={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]}[b.dataset.nudge];moveSelection(...d);}));
 $('place').addEventListener('click',()=>{if(!canPlay()||pending<0)return;if(mode==='online'){online.move(pending);return;}if(R.play(state,pending)){pending=-1;render();scheduleBot();}});
 $('undo').addEventListener('click',()=>{if(mode==='online')return;const count=undoCount();if(!count)return;cancelBot();R.undo(state,count);pending=-1;render();});
 document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{if(mode==='online'&&b.dataset.mode!=='online')online.leave();mode=b.dataset.mode;syncOptions();}));document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>{level=b.dataset.level;syncOptions();}));document.querySelectorAll('[data-color]').forEach(b=>b.addEventListener('click',()=>{human=+b.dataset.color;syncOptions();}));
 $('start').addEventListener('click',start);$('replay').addEventListener('click',()=>{if(mode==='online')online.rematch();else start();});
 $('helpOpen').addEventListener('click',()=>$('helpDialog').showModal());$('helpClose').addEventListener('click',()=>$('helpDialog').close());
 $('settings').addEventListener('click',()=>{$('newTitle').textContent=mode==='online'?'이 방에서 나갈까요?':'이번 판을 마칠까요?';$('newDialog').querySelector('p').textContent=mode==='online'?'나가도 진행 중인 판은 유지돼요. 초대 링크를 같은 브라우저에서 열면 돌아올 수 있어요.':'현재 놓인 돌은 지워져요. 새 판에서 다시 고를 수 있어요.';if(mode==='online'||state.moves.length&&!done())$('newDialog').showModal();else lobby();});$('keepPlaying').addEventListener('click',()=>$('newDialog').close());$('newGame').addEventListener('click',()=>{$('newDialog').close();lobby();});
 window.addEventListener('pagehide',cancelBot);window.addEventListener('pageshow',()=>{if(!$('game').hidden&&!busy)scheduleBot();});
 online=window.OmokOnline.attach({mode:()=>mode,setMode(value){mode=value;syncOptions();},render,apply(next,me){if(next.moves.length!==state.moves.length||next.board.some((v,i)=>v!==state.board[i]))pending=-1;state=next;human=me;}});
 syncOptions();online.init();if(params.get('guide')==='1'&&typeof $('helpDialog').showModal==='function')$('helpDialog').showModal();
})();
