const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{serve}=require('./alkkagi-preview.cjs');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/USER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const fixture=await serve(0);let browser;try{
 browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 const contexts=await Promise.all([0,1,2].map(()=>browser.newContext({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'}))),pages=await Promise.all(contexts.map(c=>c.newPage())),[host,guest,third]=pages,errors=[];
 for(const c of contexts)await c.route('**/*',r=>r.request().url().startsWith(fixture.url)||r.request().url().startsWith('data:')?r.continue():r.abort());for(const p of pages)p.on('pageerror',e=>errors.push(e.message));
 const go=(p,query='')=>p.goto(fixture.url+'/t/alkkagi/'+query),out=path.resolve('output/alkkagi-v3');fs.mkdirSync(out,{recursive:true});
 const charge=async p=>{await p.bringToFront();await p.locator('#place').click();await p.waitForFunction(()=>document.getElementById('powerMeter').classList.contains('charging')&&Number(document.getElementById('powerMeter').getAttribute('aria-valuenow'))>=75);};
 const fire=async p=>{await charge(p);await p.locator('#place').click();};
 for(const width of [320,390,768,1024]){await host.setViewportSize({width,height:900});await go(host,'?mode=local');await host.evaluate(()=>document.fonts.ready);assert(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await host.screenshot({path:path.join(out,'lobby-'+width+'.png'),fullPage:true});await host.locator('#start').click();const boardBox=await host.locator('#board').boundingBox();assert(boardBox.width>=(width<700?width-36:640),'enlarged board');assert(Math.abs(boardBox.width-boardBox.height)<1,'square physics surface');await host.locator('[data-stone="2"]').tap();assert(await host.locator('#aim').isVisible());assert.equal(await host.locator('#moveCount').innerText(),'0번');await host.locator('[data-angle="315"]').tap();await charge(host);await host.screenshot({path:path.join(out,'board-'+width+'.png'),fullPage:true});assert(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await host.locator('#place').click();assert.equal(await host.locator('#moveCount').innerText(),'1번');assert.match(await host.locator('#turnStatus').innerText(),/백돌/);}
 await host.setViewportSize({width:390,height:844});await go(host,'?mode=online&player=0');await host.locator('#nickname').fill('톡톡');await host.locator('#start').click();await host.locator('#roomPanel').waitFor();const hash=new URL(host.url()).hash;
 await host.screenshot({path:path.join(out,'invite-390.png'),fullPage:true});await go(guest,'?mode=online&player=1'+hash);await guest.waitForFunction(()=>document.getElementById('onlineIntro').textContent.includes('톡톡'));await guest.locator('#nickname').fill('반가운 친구');await guest.locator('#start').click();await host.waitForFunction(()=>document.getElementById('whiteName').textContent.includes('반가운 친구'));
 await host.locator('[data-stone="2"]').tap();await charge(host);await host.evaluate(()=>{document.getElementById('place').click();document.getElementById('place').click();});await guest.waitForFunction(()=>document.getElementById('moveCount').textContent==='1번');assert(await host.locator('#place').isDisabled());
 const positions=p=>p.locator('.alk-stone').evaluateAll(list=>list.map(s=>({left:s.style.left,top:s.style.top,hidden:s.hidden})));assert.deepEqual(await positions(host),await positions(guest));
 const available=await guest.locator('.alk-stone.white:not([hidden])').first();await guest.bringToFront();await available.tap();await fire(guest);await host.waitForFunction(()=>document.getElementById('moveCount').textContent==='2번');assert.deepEqual(await positions(host),await positions(guest));
 await host.reload();await host.locator('#roomPanel').waitFor();assert.equal(await host.locator('#moveCount').innerText(),'2번');assert.match(await host.locator('#blackName').innerText(),/톡톡 \(나\)/);
 await go(third,'?mode=online&player=2'+hash);await third.waitForFunction(()=>document.getElementById('onlineMessage').textContent.includes('이미 두 사람'));
 await host.bringToFront();await host.locator('.alk-stone.black:not([hidden])').first().tap();await charge(host);
 await contexts[0].setOffline(true);await host.waitForFunction(()=>document.getElementById('turnStatus').textContent.includes('연결'));assert(await host.locator('#place').isDisabled());assert(await host.locator('#cancelCharge').isHidden());await contexts[0].setOffline(false);await host.waitForFunction(()=>document.getElementById('turnStatus').textContent.startsWith('내 차례'));
 await guest.locator('#resign').click();await guest.locator('#resignConfirm').click();await host.locator('#result').waitFor();await host.locator('#replay').click();await host.waitForFunction(()=>document.getElementById('replay').disabled);assert.equal(await host.locator('#moveCount').innerText(),'2번');await guest.locator('#replay').click();await host.waitForFunction(()=>document.getElementById('moveCount').textContent==='0번');assert.equal(await host.locator('.alk-stone:not([hidden])').count(),10);
 assert.match(await host.locator('#roomNote').innerText(),/백돌부터/);assert.match(await guest.locator('#turnStatus').innerText(),/내 차례/);
 await host.screenshot({path:path.join(out,'online-390.png'),fullPage:true});
 // Real animation must settle, unlock the next turn and prevent repeated shots during motion.
 await host.emulateMedia({reducedMotion:'no-preference'});await go(host,'?mode=local');await host.locator('#start').click();await host.locator('[data-stone="2"]').tap();await fire(host);assert(await host.locator('#place').isDisabled());await host.waitForFunction(()=>document.getElementById('turnStatus').textContent.startsWith('백돌'),{},{timeout:10000});assert.equal(await host.locator('#moveCount').innerText(),'1번');
 await go(host);await host.locator('#start').click();await host.locator('[data-stone="2"]').tap();await fire(host);await host.waitForFunction(()=>document.getElementById('moveCount').textContent==='2번'&&document.getElementById('turnStatus').textContent.startsWith('내 차례'),{},{timeout:15000});
 await go(host,'?mode=local');await host.locator('#start').click();await host.locator('[data-stone="1"]').tap();
 const aim=await host.locator('#aimLine').getAttribute('y2');await charge(host);await host.waitForFunction(()=>Number(document.getElementById('powerMeter').getAttribute('aria-valuenow'))>=95);await host.waitForFunction(()=>Number(document.getElementById('powerMeter').getAttribute('aria-valuenow'))<50);
 assert.equal(await host.locator('#aimLine').getAttribute('y2'),aim);assert(await host.locator('[data-angle="90"]').isDisabled());await host.locator('#cancelCharge').click();assert.equal(await host.locator('#moveCount').innerText(),'0번');
 await host.locator('#place').focus();await host.keyboard.press('Space');await host.waitForTimeout(500);await host.keyboard.press('Space');await host.waitForFunction(()=>document.getElementById('moveCount').textContent==='1번');
 await go(host,'?guide=1');assert(await host.locator('#helpDialog').isVisible());await host.locator('#helpClose').click();
 await host.goto(fixture.url+'/?home=play#all');await host.locator('a[href="t/alkkagi/?mode=online"]').waitFor();await host.goto(fixture.url+'/?tab=solo#all');await host.locator('a[href="t/alkkagi/?solo=1"]').waitFor();
 assert.deepEqual(errors,[]);console.log('PASS Alkkagi browser: responsive UI, aiming/power, animated collision, AI, two authenticated players, identical positions, duplicate protection, resume, disconnect, full room, mutual rematch and home entries');
 }finally{if(browser)await browser.close();await fixture.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
