-- 이미 적용된 단톡방 게임 서버를 2명 대결에도 열어 준다.
alter table public.party_rooms drop constraint if exists party_rooms_max_players_check;
alter table public.party_rooms add constraint party_rooms_max_players_check check (max_players between 2 and 12);

create or replace function public.create_party_room(p_game text,p_stake_text text,p_nickname text,p_max_players integer default 4) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.party_rooms%rowtype; n text:=btrim(p_nickname); s text:=btrim(p_stake_text); begin if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; if p_game not in ('rps','nunchi','choseong','balance','bomb') then raise exception 'INVALID_GAME'; end if; if char_length(n) not between 1 and 12 then raise exception 'INVALID_NICKNAME'; end if; if char_length(s) not between 1 and 40 then raise exception 'INVALID_STAKE'; end if; if p_max_players not between 2 and 12 then raise exception 'INVALID_MAX_PLAYERS'; end if; insert into public.party_rooms(host_user_id,game,stake_text,max_players) values(auth.uid(),p_game,s,p_max_players) returning * into r; insert into public.party_members(room_id,user_id,nickname,role,is_ready) values(r.id,auth.uid(),n,'host',true); return public.party_snapshot(r); end $$;

create or replace function public.start_party_room(p_room_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.party_rooms%rowtype; ids jsonb; c int; u int; st jsonb; begin select * into r from public.party_rooms where id=p_room_id for update; if not found then raise exception 'ROOM_NOT_FOUND'; end if; if r.host_user_id<>auth.uid() then raise exception 'HOST_ONLY'; end if; if r.status<>'lobby' then raise exception 'ROOM_ALREADY_STARTED'; end if; select count(*),count(*)filter(where not is_ready) into c,u from public.party_members where room_id=r.id; if c<2 then raise exception 'NEED_MORE_PLAYERS'; end if; if u>0 then raise exception 'MEMBERS_NOT_READY'; end if; select jsonb_agg(id order by joined_at) into ids from public.party_members where room_id=r.id; st=jsonb_build_object('phase','input','candidates',ids,'question_index',0); if r.game='choseong' then st=st||jsonb_build_object('turn_index',0,'turn_member_id',ids->>0,'scores','{}'::jsonb,'question',public.party_question(0)); elsif r.game='balance' then st=st||jsonb_build_object('question_index',floor(random()*6)::int); elsif r.game='bomb' then st=st||jsonb_build_object('holder_member_id',ids->>floor(random()*c)::int,'bomb_at',now()+interval '15 seconds'+(floor(random()*16)::text||' seconds')::interval); end if; update public.party_rooms set status='playing',state=st,updated_at=now() where id=r.id returning * into r; return public.party_snapshot(r); end $$;
