-- 같이놀자 관리자 모드
-- 공개 사이트는 get_published_app_config()만 읽고, 초안/게시/복원은 관리자만 실행한다.

create extension if not exists pgcrypto;

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '운영자',
  role text not null default 'owner' check (role in ('owner', 'editor')),
  created_at timestamptz not null default now()
);

create table if not exists public.app_config_state (
  id text primary key default 'main' check (id = 'main'),
  draft jsonb,
  draft_note text,
  draft_updated_by uuid references auth.users(id),
  draft_updated_at timestamptz,
  published jsonb,
  published_by uuid references auth.users(id),
  published_at timestamptz,
  version integer not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.app_config_state (id) values ('main') on conflict (id) do nothing;

create table if not exists public.app_config_versions (
  id bigint generated by default as identity primary key,
  version integer not null unique,
  config jsonb not null,
  note text,
  published_by uuid references auth.users(id),
  published_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  game_slug text not null default 'home',
  entry_type text not null default 'direct',
  share_method text,
  session_id text,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);
create index if not exists analytics_events_game_event_idx
  on public.analytics_events (game_slug, event_name, created_at desc);

alter table public.app_admins enable row level security;
alter table public.app_config_state enable row level security;
alter table public.app_config_versions enable row level security;
alter table public.analytics_events enable row level security;

revoke all on public.app_admins from anon, authenticated;
revoke all on public.app_config_state from anon, authenticated;
revoke all on public.app_config_versions from anon, authenticated;
revoke all on public.analytics_events from anon, authenticated;

create or replace function public.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.app_admins a where a.user_id = (select auth.uid())
  );
$$;

create or replace function public.get_published_app_config()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select s.published from public.app_config_state s where s.id = 'main';
$$;

create or replace function public.admin_get_app_state()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_state public.app_config_state%rowtype;
  v_admin public.app_admins%rowtype;
begin
  select * into v_admin from public.app_admins where user_id = (select auth.uid());
  if not found then raise exception 'ADMIN_REQUIRED'; end if;

  select * into v_state from public.app_config_state where id = 'main';
  return jsonb_build_object(
    'admin', jsonb_build_object('name', v_admin.display_name, 'role', v_admin.role),
    'draft', v_state.draft,
    'draft_note', v_state.draft_note,
    'draft_updated_at', v_state.draft_updated_at,
    'published', v_state.published,
    'published_at', v_state.published_at,
    'version', v_state.version,
    'versions', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', v.id,
        'version', v.version,
        'note', v.note,
        'published_at', v.published_at,
        'published_by', v.published_by
      ) order by v.version desc)
      from (select * from public.app_config_versions order by version desc limit 30) v
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.validate_app_config(p_config jsonb)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
begin
  if p_config is null or jsonb_typeof(p_config) <> 'object' then
    raise exception 'INVALID_CONFIG';
  end if;
  if jsonb_typeof(p_config->'site') <> 'object'
     or jsonb_typeof(p_config->'games') <> 'array'
     or jsonb_typeof(p_config->'ads') <> 'object' then
    raise exception 'INVALID_CONFIG_SHAPE';
  end if;
  if jsonb_array_length(p_config->'games') > 100 then
    raise exception 'TOO_MANY_GAMES';
  end if;
  if char_length(coalesce(p_config#>>'{site,name}', '')) not between 1 and 40 then
    raise exception 'INVALID_SITE_NAME';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_config->'games') g
    where char_length(coalesce(g->>'slug', '')) not between 1 and 50
       or coalesce(g->>'slug', '') !~ '^[a-z0-9][a-z0-9/_-]*$'
       or char_length(coalesce(g->>'title', '')) not between 1 and 80
       or char_length(coalesce(g->>'summary', '')) > 180
       or coalesce(g->>'path', '') !~ '^t/[a-z0-9][a-z0-9/_-]*/$'
       or coalesce(g->>'visibility', 'listed') not in ('listed', 'hidden', 'maintenance')
  ) then
    raise exception 'INVALID_GAME';
  end if;
  if jsonb_typeof(p_config#>'{site,menu}') <> 'array'
     or jsonb_array_length(p_config#>'{site,menu}') > 10
     or exists (
       select 1 from jsonb_array_elements(p_config#>'{site,menu}') m
       where char_length(coalesce(m->>'label', '')) not between 1 and 30
          or left(coalesce(m->>'href', ''), 2) = '//'
          or position(':' in coalesce(m->>'href', '')) > 0
          or position(chr(92) in coalesce(m->>'href', '')) > 0
     ) then
    raise exception 'INVALID_MENU';
  end if;
  if jsonb_typeof(p_config#>'{ads,slots}') <> 'array'
     or jsonb_array_length(p_config#>'{ads,slots}') > 20
     or exists (
       select 1 from jsonb_array_elements(p_config#>'{ads,slots}') a
       where coalesce(a->>'placement', '') not in ('result_bottom', 'home_catalog', 'recommendation_top')
          or (coalesce(a->>'linkUrl', '') <> '' and coalesce(a->>'linkUrl', '') !~ '^https://')
          or (coalesce(a->>'imageUrl', '') <> '' and coalesce(a->>'imageUrl', '') !~ '^https://')
     ) then
    raise exception 'INVALID_AD';
  end if;
  return true;
end;
$$;

create or replace function public.admin_save_app_draft(
  p_config jsonb,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_app_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  perform public.validate_app_config(p_config);
  update public.app_config_state
  set draft = p_config,
      draft_note = nullif(left(btrim(coalesce(p_note, '')), 200), ''),
      draft_updated_by = (select auth.uid()),
      draft_updated_at = now(),
      updated_at = now()
  where id = 'main';
  return jsonb_build_object('ok', true, 'saved_at', now());
end;
$$;

create or replace function public.admin_publish_app_config(
  p_config jsonb,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_version integer;
  v_note text := nullif(left(btrim(coalesce(p_note, '')), 200), '');
begin
  if not public.is_app_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  perform public.validate_app_config(p_config);

  update public.app_config_state
  set draft = p_config,
      draft_note = v_note,
      draft_updated_by = (select auth.uid()),
      draft_updated_at = now(),
      published = p_config,
      published_by = (select auth.uid()),
      published_at = now(),
      version = version + 1,
      updated_at = now()
  where id = 'main'
  returning version into v_version;

  insert into public.app_config_versions (version, config, note, published_by)
  values (v_version, p_config, v_note, (select auth.uid()));

  return jsonb_build_object('ok', true, 'version', v_version, 'published_at', now());
end;
$$;

create or replace function public.admin_restore_app_version(
  p_version integer,
  p_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_config jsonb;
  v_new_version integer;
  v_note text;
begin
  if not public.is_app_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select config into v_config from public.app_config_versions where version = p_version;
  if not found then raise exception 'VERSION_NOT_FOUND'; end if;
  v_note := coalesce(nullif(left(btrim(coalesce(p_note, '')), 200), ''), p_version || '번 버전 복원');

  update public.app_config_state
  set draft = v_config,
      draft_note = v_note,
      draft_updated_by = (select auth.uid()),
      draft_updated_at = now(),
      published = v_config,
      published_by = (select auth.uid()),
      published_at = now(),
      version = version + 1,
      updated_at = now()
  where id = 'main'
  returning version into v_new_version;

  insert into public.app_config_versions (version, config, note, published_by)
  values (v_new_version, v_config, v_note, (select auth.uid()));
  return jsonb_build_object('ok', true, 'version', v_new_version, 'restored_from', p_version);
end;
$$;

create or replace function public.track_app_event(
  p_event text,
  p_game text default 'home',
  p_entry text default 'direct',
  p_method text default null,
  p_session_id text default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_event not in (
    'page_view', 'game_started', 'game_completed', 'link_made', 'invite_opened',
    'responded', 'invite_shared', 'result_opened', 'result_shared', 'replay',
    'letter_opened', 'ad_viewed', 'ad_clicked'
  ) then return false; end if;
  insert into public.analytics_events (event_name, game_slug, entry_type, share_method, session_id)
  values (
    p_event,
    left(regexp_replace(coalesce(p_game, 'home'), '[^a-zA-Z0-9/_-]', '', 'g'), 50),
    left(coalesce(p_entry, 'direct'), 20),
    nullif(left(coalesce(p_method, ''), 20), ''),
    nullif(left(coalesce(p_session_id, ''), 40), '')
  );
  return true;
end;
$$;

create or replace function public.admin_get_app_stats(p_days integer default 7)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_days integer := greatest(1, least(coalesce(p_days, 7), 90));
  v_since timestamptz;
begin
  if not public.is_app_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  v_since := now() - make_interval(days => v_days);
  return jsonb_build_object(
    'days', v_days,
    'totals', coalesce((
      select jsonb_object_agg(event_name, count)
      from (
        select event_name, count(*)::integer as count
        from public.analytics_events where created_at >= v_since
        group by event_name
      ) e
    ), '{}'::jsonb),
    'visitors', (select count(distinct session_id)::integer from public.analytics_events where created_at >= v_since and session_id is not null),
    'games', coalesce((
      select jsonb_agg(jsonb_build_object(
        'slug', game_slug,
        'visits', visits,
        'starts', starts,
        'completes', completes,
        'shares', shares,
        'invite_opens', invite_opens,
        'responses', responses,
        'replays', replays
      ) order by visits desc)
      from (
        select game_slug,
          count(*) filter (where event_name = 'page_view')::integer visits,
          count(*) filter (where event_name = 'game_started')::integer starts,
          count(*) filter (where event_name = 'game_completed')::integer completes,
          count(*) filter (where event_name = 'invite_shared')::integer shares,
          count(*) filter (where event_name = 'invite_opened')::integer invite_opens,
          count(*) filter (where event_name = 'responded')::integer responses,
          count(*) filter (where event_name = 'replay')::integer replays
        from public.analytics_events where created_at >= v_since
        group by game_slug
      ) g
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function public.is_app_admin() from public, anon;
revoke all on function public.get_published_app_config() from public;
revoke all on function public.admin_get_app_state() from public, anon;
revoke all on function public.validate_app_config(jsonb) from public, anon, authenticated;
revoke all on function public.admin_save_app_draft(jsonb, text) from public, anon;
revoke all on function public.admin_publish_app_config(jsonb, text) from public, anon;
revoke all on function public.admin_restore_app_version(integer, text) from public, anon;
revoke all on function public.track_app_event(text, text, text, text, text) from public;
revoke all on function public.admin_get_app_stats(integer) from public, anon;

grant execute on function public.get_published_app_config() to anon, authenticated;
grant execute on function public.is_app_admin() to authenticated;
grant execute on function public.admin_get_app_state() to authenticated;
grant execute on function public.admin_save_app_draft(jsonb, text) to authenticated;
grant execute on function public.admin_publish_app_config(jsonb, text) to authenticated;
grant execute on function public.admin_restore_app_version(integer, text) to authenticated;
grant execute on function public.track_app_event(text, text, text, text, text) to anon, authenticated;
grant execute on function public.admin_get_app_stats(integer) to authenticated;

-- 관리자에서 올리는 썸네일·배너. 읽기는 공개, 쓰기는 app_admins에 등록된 계정만 가능하다.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('admin-assets', 'admin-assets', true, 2097152, array['image/png', 'image/jpeg', 'image/webp', 'image/gif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "app admins upload managed assets" on storage.objects;
drop policy if exists "app admins update managed assets" on storage.objects;
drop policy if exists "app admins delete managed assets" on storage.objects;
create policy "app admins upload managed assets" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'admin-assets' and public.is_app_admin());
create policy "app admins update managed assets" on storage.objects
  for update to authenticated
  using (bucket_id = 'admin-assets' and public.is_app_admin())
  with check (bucket_id = 'admin-assets' and public.is_app_admin());
create policy "app admins delete managed assets" on storage.objects
  for delete to authenticated
  using (bucket_id = 'admin-assets' and public.is_app_admin());

-- 첫 관리자 등록은 Authentication > Users에서 계정을 만든 뒤 아래 예시를 별도로 실행한다.
-- insert into public.app_admins (user_id, display_name, role)
-- values ('Authentication 화면의 User UID', '운영자', 'owner');

select 'admin_center_ready' as result;
