-- 단톡방 벌칙전: 기존 group_rooms와 별개로 다섯 게임의 라운드 상태를 보관한다.
-- 이 파일을 Supabase SQL Editor에서 한 번 실행하면 /t/group-room/ 화면이 활성화된다.
create extension if not exists pgcrypto;

create table if not exists public.party_rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique default upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)),
  host_user_id uuid not null references auth.users(id) on delete cascade,
  game text not null check (game in ('rps','nunchi','choseong','balance','bomb')),
  stake_text text not null check (char_length(btrim(stake_text)) between 1 and 40),
  max_players smallint not null check (max_players between 3 and 12),
  status text not null default 'lobby' check (status in ('lobby','playing','finished','cancelled')),
  current_round smallint not null default 1,
  state jsonb not null default '{"phase":"input"}'::jsonb,
  result jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '24 hours'
);
create table if not exists public.party_members (
  id uuid primary key default gen_random_uuid(), room_id uuid not null references public.party_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, nickname text not null check(char_length(btrim(nickname)) between 1 and 12),
  role text not null default 'player' check(role in ('host','player')), is_ready boolean not null default false, is_active boolean not null default true, joined_at timestamptz not null default now(),
  unique(room_id,user_id), unique(room_id,nickname)
);
create table if not exists public.party_moves (
  id uuid primary key default gen_random_uuid(), room_id uuid not null references public.party_rooms(id) on delete cascade,
  member_id uuid not null references public.party_members(id) on delete cascade, round_no smallint not null, move jsonb not null, submitted_at timestamptz not null default now(), unique(room_id,member_id,round_no)
);
create index if not exists party_rooms_code_idx on public.party_rooms(code);
create index if not exists party_members_room_idx on public.party_members(room_id);
create index if not exists party_moves_round_idx on public.party_moves(room_id,round_no);
alter table public.party_rooms enable row level security; alter table public.party_members enable row level security; alter table public.party_moves enable row level security;
revoke all on public.party_rooms,public.party_members,public.party_moves from anon,authenticated;

create or replace function public.party_question(p_index integer) returns jsonb language sql immutable set search_path='' as $$
 select (array[
  '{"prompt":"ㄸㅂㅇ","answer":"떡볶이"}'::jsonb,'{"prompt":"ㅂㄴㄴ","answer":"바나나"}'::jsonb,'{"prompt":"ㅊㅋ","answer":"치킨"}'::jsonb,
  '{"prompt":"ㅎㅂㄱ","answer":"햄버거"}'::jsonb,'{"prompt":"ㅇㅇㅋㄹ","answer":"아이스크림"}'::jsonb,'{"prompt":"ㅅㅁㅌ","answer":"스마트폰"}'::jsonb,
  '{"prompt":"ㅇㅎ","answer":"영화"}'::jsonb,'{"prompt":"ㄱㅇㅂㅇㅂ","answer":"가위바위보"}'::jsonb,'{"prompt":"ㄴㅊㄱㅇ","answer":"눈치게임"}'::jsonb,
  '{"prompt":"ㄷㅌㅂ","answer":"단톡방"}'::jsonb,'{"prompt":"ㅋㅍ","answer":"커피"}'::jsonb,'{"prompt":"ㅇㅇㅅㅋㄹ","answer":"아이스크림"}'::jsonb
  ])[1+(abs(p_index)%12)];
$$;

create or replace function public.party_is_member(p_room uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.party_members where room_id=p_room and user_id=auth.uid());
$$;

-- 상태 조회는 모든 읽기를 이 RPC 하나로 제한한다. 진행 중 상대의 선택은 submitted 여부만 보인다.
create or replace function public.party_snapshot(p_room public.party_rooms) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_moves jsonb:='[]'::jsonb; v_members jsonb;
begin
 select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'nickname',m.nickname,'role',m.role,'is_ready',m.is_ready,'is_active',m.is_active,'is_me',m.user_id=auth.uid(),'has_submitted',exists(select 1 from public.party_moves x where x.room_id=p_room.id and x.member_id=m.id and x.round_no=p_room.current_round)) order by m.joined_at),'[]'::jsonb) into v_members from public.party_members m where m.room_id=p_room.id;
 if p_room.status='finished' or coalesce(p_room.state->>'phase','')='revealed' then
   select coalesce(jsonb_agg(jsonb_build_object('nickname',m.nickname,'move',x.move) order by m.joined_at),'[]'::jsonb) into v_moves from public.party_moves x join public.party_members m on m.id=x.member_id where x.room_id=p_room.id and x.round_no=p_room.current_round;
 end if;
 return jsonb_build_object('room',jsonb_build_object('id',p_room.id,'code',p_room.code,'game',p_room.game,'stake_text',p_room.stake_text,'max_players',p_room.max_players,'status',p_room.status,'current_round',p_room.current_round,'is_host',p_room.host_user_id=auth.uid(),'state',p_room.state,'result',p_room.result),'members',v_members,'moves',v_moves);
end $$;

create or replace function public.peek_party_room(p_code text) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare r public.party_rooms%rowtype; begin select * into r from public.party_rooms where code=upper(btrim(p_code)); if not found then raise exception 'ROOM_NOT_FOUND'; end if; return jsonb_build_object('code',r.code,'game',r.game); end $$;
create or replace function public.get_party_room(p_code text) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.party_rooms%rowtype; v_holder uuid; begin select * into r from public.party_rooms where code=upper(btrim(p_code)) for update; if not found then raise exception 'ROOM_NOT_FOUND'; end if; if not public.party_is_member(r.id) then raise exception 'ROOM_ACCESS_DENIED'; end if;
 if r.game='bomb' and r.status='playing' and (r.state->>'bomb_at')::timestamptz<=now() then v_holder:=(r.state->>'holder_member_id')::uuid; update public.party_rooms set status='finished',result=jsonb_build_object('loser_member_id',v_holder,'loser_nickname',(select nickname from public.party_members where id=v_holder),'stake_text',r.stake_text),updated_at=now() where id=r.id returning * into r; end if;
 return public.party_snapshot(r); end $$;

create or replace function public.create_party_room(p_game text,p_stake_text text,p_nickname text,p_max_players integer default 4) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.party_rooms%rowtype; n text:=btrim(p_nickname); s text:=btrim(p_stake_text); begin if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; if p_game not in ('rps','nunchi','choseong','balance','bomb') then raise exception 'INVALID_GAME'; end if; if char_length(n) not between 1 and 12 then raise exception 'INVALID_NICKNAME'; end if; if char_length(s) not between 1 and 40 then raise exception 'INVALID_STAKE'; end if; if p_max_players not between 3 and 12 then raise exception 'INVALID_MAX_PLAYERS'; end if;
 insert into public.party_rooms(host_user_id,game,stake_text,max_players) values(auth.uid(),p_game,s,p_max_players) returning * into r; insert into public.party_members(room_id,user_id,nickname,role,is_ready) values(r.id,auth.uid(),n,'host',true); return public.party_snapshot(r); end $$;
create or replace function public.join_party_room(p_code text,p_nickname text) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.party_rooms%rowtype; n text:=btrim(p_nickname); c int; begin if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if; if char_length(n) not between 1 and 12 then raise exception 'INVALID_NICKNAME'; end if; select * into r from public.party_rooms where code=upper(btrim(p_code)) for update; if not found then raise exception 'ROOM_NOT_FOUND'; end if; if r.status<>'lobby' then raise exception 'ROOM_ALREADY_STARTED'; end if; if r.expires_at<=now() then raise exception 'ROOM_EXPIRED'; end if; if exists(select 1 from public.party_members where room_id=r.id and user_id=auth.uid()) then return public.party_snapshot(r); end if; if exists(select 1 from public.party_members where room_id=r.id and nickname=n) then raise exception 'NICKNAME_ALREADY_USED'; end if; select count(*) into c from public.party_members where room_id=r.id; if c>=r.max_players then raise exception 'ROOM_FULL'; end if; insert into public.party_members(room_id,user_id,nickname) values(r.id,auth.uid(),n); return public.party_snapshot(r); end $$;
create or replace function public.set_party_ready(p_room_id uuid,p_ready boolean) returns jsonb language plpgsql security definer set search_path='' as $$ declare r public.party_rooms%rowtype; begin select * into r from public.party_rooms where id=p_room_id; if not found then raise exception 'ROOM_NOT_FOUND'; end if; update public.party_members set is_ready=p_ready where room_id=r.id and user_id=auth.uid(); if not found then raise exception 'MEMBER_NOT_FOUND'; end if; return public.party_snapshot(r); end $$;
create or replace function public.start_party_room(p_room_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.party_rooms%rowtype; ids jsonb; c int; u int; st jsonb; begin select * into r from public.party_rooms where id=p_room_id for update; if not found then raise exception 'ROOM_NOT_FOUND'; end if; if r.host_user_id<>auth.uid() then raise exception 'HOST_ONLY'; end if; if r.status<>'lobby' then raise exception 'ROOM_ALREADY_STARTED'; end if; select count(*),count(*)filter(where not is_ready) into c,u from public.party_members where room_id=r.id; if c<3 then raise exception 'NEED_MORE_PLAYERS'; end if; if u>0 then raise exception 'MEMBERS_NOT_READY'; end if; select jsonb_agg(id order by joined_at) into ids from public.party_members where room_id=r.id;
 st=jsonb_build_object('phase','input','candidates',ids,'question_index',0); if r.game='choseong' then st=st||jsonb_build_object('turn_index',0,'turn_member_id',ids->>0,'scores','{}'::jsonb,'question',public.party_question(0)); elsif r.game='balance' then st=st||jsonb_build_object('question_index',floor(random()*6)::int); elsif r.game='bomb' then st=st||jsonb_build_object('holder_member_id',ids->>floor(random()*c)::int,'bomb_at',now()+interval '15 seconds'+(floor(random()*16)::text||' seconds')::interval); end if; update public.party_rooms set status='playing',state=st,updated_at=now() where id=r.id returning * into r; return public.party_snapshot(r); end $$;

create or replace function public.party_finish(p_room_id uuid,p_loser uuid) returns public.party_rooms language plpgsql security definer set search_path='' as $$ declare r public.party_rooms%rowtype; begin update public.party_rooms set status='finished',result=jsonb_build_object('loser_member_id',p_loser,'loser_nickname',(select nickname from public.party_members where id=p_loser),'stake_text',(select stake_text from public.party_rooms where id=p_room_id)),updated_at=now() where id=p_room_id returning * into r; return r; end $$;

-- 전원 비밀 선택형 세 게임 판정. 탈출한 사람은 inactive, 마지막 active 한 명이 벌칙이다.
create or replace function public.party_resolve_vote(p_room_id uuid) returns public.party_rooms language plpgsql security definer set search_path='' as $$
declare r public.party_rooms%rowtype; keep jsonb:='[]'::jsonb; c int; low int; h text; begin select * into r from public.party_rooms where id=p_room_id for update; if r.game='rps' then
 select count(distinct move->>'hand') into c from public.party_moves where room_id=r.id and round_no=r.current_round; if c<>2 then update public.party_rooms set state=state||jsonb_build_object('phase','revealed','message','같은 손 또는 세 손이 나왔어요. 모두 다시!') where id=r.id returning * into r; return r; end if;
 select (move->>'hand') into h from public.party_moves where room_id=r.id and round_no=r.current_round group by move->>'hand' order by count(*) limit 1; -- below derives losing hand from the two displayed hands
 select case when bool_or(move->>'hand'='rock') and bool_or(move->>'hand'='scissors') then 'scissors' when bool_or(move->>'hand'='scissors') and bool_or(move->>'hand'='paper') then 'paper' else 'rock' end into h from public.party_moves where room_id=r.id and round_no=r.current_round;
 select jsonb_agg(member_id) into keep from public.party_moves where room_id=r.id and round_no=r.current_round and move->>'hand'=h;
 elsif r.game='nunchi' then select min(n) into low from (select (move->>'number')::int n from public.party_moves where room_id=r.id and round_no=r.current_round group by (move->>'number')::int having count(*)=1) unique_numbers; if low is null then update public.party_rooms set state=state||jsonb_build_object('phase','revealed','message','겹쳤어요! 아무도 탈출하지 못했어요.') where id=r.id returning * into r; return r; end if; select jsonb_agg(member_id) into keep from public.party_moves where room_id=r.id and round_no=r.current_round and (move->>'number')::int<>low;
 else select count(*) into c from public.party_moves where room_id=r.id and round_no=r.current_round and move->>'choice'='a'; if c=0 or c=(select count(*) from public.party_moves where room_id=r.id and round_no=r.current_round) then update public.party_rooms set state=state||jsonb_build_object('phase','revealed','message','모두 같은 쪽! 다시 골라요.') where id=r.id returning * into r; return r; end if; if c=(select count(*)-c from public.party_moves where room_id=r.id and round_no=r.current_round) then update public.party_rooms set state=state||jsonb_build_object('phase','revealed','message','정확히 반반! 다시 골라요.') where id=r.id returning * into r; return r; end if; select jsonb_agg(member_id) into keep from public.party_moves where room_id=r.id and round_no=r.current_round and move->>'choice'=case when c<(select count(*)-c from public.party_moves where room_id=r.id and round_no=r.current_round) then 'a' else 'b' end; end if;
 update public.party_members set is_active=(id in (select jsonb_array_elements_text(coalesce(keep,'[]'::jsonb))::uuid)) where room_id=r.id; select count(*) into c from public.party_members where room_id=r.id and is_active; if c=1 then return public.party_finish(r.id,(select id from public.party_members where room_id=r.id and is_active)); end if; update public.party_rooms set state=state||jsonb_build_object('phase','revealed','candidates',coalesce(keep,'[]'::jsonb),'message',case r.game when 'nunchi' then '가장 낮은 유일 숫자는 탈출 성공! 남은 사람끼리 계속.' when 'balance' then '소수 의견만 다음 라운드로!' else '진 손만 다음 라운드로!' end),updated_at=now() where id=r.id returning * into r; return r; end $$;

create or replace function public.submit_party_move(p_room_id uuid,p_move jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.party_rooms%rowtype; m public.party_members%rowtype; need int; got int; q jsonb; score int; nexti int; new_scores jsonb; lowest int; tied int; loser uuid; tied_ids jsonb; begin select * into r from public.party_rooms where id=p_room_id for update; if not found then raise exception 'ROOM_NOT_FOUND'; end if; if r.status<>'playing' then raise exception 'ROOM_NOT_PLAYING'; end if; select * into m from public.party_members where room_id=r.id and user_id=auth.uid(); if not found or not m.is_active then raise exception 'MEMBER_NOT_ACTIVE'; end if; if exists(select 1 from public.party_moves where room_id=r.id and member_id=m.id and round_no=r.current_round) then raise exception 'ALREADY_SUBMITTED'; end if;
 if r.game='choseong' then if (r.state->>'turn_member_id')::uuid<>m.id then raise exception 'NOT_YOUR_TURN'; end if; q:=r.state->'question'; score:=case when lower(regexp_replace(coalesce(p_move->>'answer',''),'\\s','','g'))=lower(q->>'answer') then 1 else 0 end; insert into public.party_moves(room_id,member_id,round_no,move) values(r.id,m.id,r.current_round,jsonb_build_object('answer',p_move->>'answer','correct',score=1)); new_scores:=jsonb_set(coalesce(r.state->'scores','{}'::jsonb),array[m.id::text],to_jsonb(coalesce((r.state->'scores'->>m.id::text)::int,0)+score),true); nexti:=(r.state->>'turn_index')::int+1; if nexti >= jsonb_array_length(r.state->'candidates')*5 then select min(coalesce((new_scores->>id::text)::int,0)) into lowest from public.party_members where room_id=r.id and is_active; select count(*),jsonb_agg(id) into tied,tied_ids from public.party_members where room_id=r.id and is_active and coalesce((new_scores->>id::text)::int,0)=lowest; if tied=1 then select id into loser from public.party_members where room_id=r.id and is_active and coalesce((new_scores->>id::text)::int,0)=lowest; perform public.party_finish(r.id,loser); else update public.party_members set is_active=(id in(select jsonb_array_elements_text(tied_ids)::uuid)) where room_id=r.id; update public.party_rooms set state=r.state||jsonb_build_object('phase','revealed','scores',new_scores,'candidates',tied_ids,'message','최저 점수가 동점이에요. 동점자끼리 5문제 연장전!') where id=r.id; end if; else update public.party_rooms set state=r.state||jsonb_build_object('turn_index',nexti,'turn_member_id',r.state->'candidates'->>(nexti%jsonb_array_length(r.state->'candidates')),'question_index',(r.state->>'question_index')::int+1,'question',public.party_question((r.state->>'question_index')::int+1),'scores',new_scores) where id=r.id; end if; return public.get_party_room(r.code); end if;
 if r.game='rps' and coalesce(p_move->>'hand','') not in ('rock','paper','scissors') then raise exception 'INVALID_MOVE'; end if; if r.game='nunchi' and coalesce((p_move->>'number')::int,0) not between 1 and 10 then raise exception 'INVALID_MOVE'; end if; if r.game='balance' and coalesce(p_move->>'choice','') not in ('a','b') then raise exception 'INVALID_MOVE'; end if; insert into public.party_moves(room_id,member_id,round_no,move) values(r.id,m.id,r.current_round,p_move); select count(*) into need from public.party_members where room_id=r.id and is_active; select count(*) into got from public.party_moves where room_id=r.id and round_no=r.current_round; if need=got then perform public.party_resolve_vote(r.id); end if; return public.get_party_room(r.code); end $$;

create or replace function public.next_party_round(p_room_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare r public.party_rooms%rowtype; st jsonb; ids jsonb; begin select * into r from public.party_rooms where id=p_room_id for update; if not found then raise exception 'ROOM_NOT_FOUND'; end if; if r.host_user_id<>auth.uid() then raise exception 'HOST_ONLY'; end if; if r.status<>'playing' or r.state->>'phase'<>'revealed' then raise exception 'ROUND_NOT_READY'; end if; select jsonb_agg(id order by joined_at) into ids from public.party_members where room_id=r.id and is_active; st=jsonb_build_object('phase','input','candidates',ids,'question_index',(coalesce((r.state->>'question_index')::int,0)+1)); if r.game='balance' then st=st||jsonb_build_object('question_index',floor(random()*6)::int); elsif r.game='choseong' then st=st||jsonb_build_object('turn_index',0,'turn_member_id',ids->>0,'scores','{}'::jsonb,'question',public.party_question((r.state->>'question_index')::int+1)); end if; update public.party_rooms set current_round=current_round+1,state=st,updated_at=now() where id=r.id returning * into r; return public.party_snapshot(r); end $$;
create or replace function public.pass_party_bomb(p_room_id uuid,p_to_member_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare r public.party_rooms%rowtype; h uuid; begin select * into r from public.party_rooms where id=p_room_id for update; if not found then raise exception 'ROOM_NOT_FOUND'; end if; if r.game<>'bomb' or r.status<>'playing' then raise exception 'ROOM_NOT_PLAYING'; end if; h:=(r.state->>'holder_member_id')::uuid; if (r.state->>'bomb_at')::timestamptz<=now() then perform public.party_finish(r.id,h); return public.get_party_room(r.code); end if; if not exists(select 1 from public.party_members where id=h and user_id=auth.uid()) then raise exception 'NOT_BOMB_HOLDER'; end if; if not exists(select 1 from public.party_members where id=p_to_member_id and room_id=r.id and is_active) then raise exception 'INVALID_TARGET'; end if; update public.party_rooms set state=jsonb_set(state,'{holder_member_id}',to_jsonb(p_to_member_id::text)),updated_at=now() where id=r.id; return public.get_party_room(r.code); end $$;

revoke all on function public.party_question(integer),public.party_is_member(uuid),public.party_snapshot(public.party_rooms),public.peek_party_room(text),public.get_party_room(text),public.create_party_room(text,text,text,integer),public.join_party_room(text,text),public.set_party_ready(uuid,boolean),public.start_party_room(uuid),public.party_finish(uuid,uuid),public.party_resolve_vote(uuid),public.submit_party_move(uuid,jsonb),public.next_party_round(uuid),public.pass_party_bomb(uuid,uuid) from public,anon;
grant execute on function public.peek_party_room(text),public.get_party_room(text),public.create_party_room(text,text,text,integer),public.join_party_room(text,text),public.set_party_ready(uuid,boolean),public.start_party_room(uuid),public.submit_party_move(uuid,jsonb),public.next_party_round(uuid),public.pass_party_bomb(uuid,uuid) to authenticated;
