(()=>{'use strict';
const $=id=>document.getElementById(id),query=new URLSearchParams(location.search),icon={star:'M24 4 30 17 44 19 34 29 36 43 24 36 11 43 14 29 4 19 18 17Z',spoon:'M17 24C3 22 7 3 16 4S31 20 21 24L39 42Q39 47 35 43Z',crown:'M8 35 5 13 17 23 24 7 31 23 43 13 40 35ZM9 40H39',fish:'M13 24Q26 6 44 24Q26 42 13 24L3 15V33ZM35 22h.1M29 15Q23 24 29 33',key:'M27 21A10 10 0 1 0 19 23V43H26V36H32V31H26V23ZM18 12a3 3 0 1 0 6 0 3 3 0 1 0-6 0',umbrella:'M22 17V9C22 0 10 1 10 9M11 17Q22 24 34 17L24 43ZM22 20 24 43M24 43V47',heart:'M24 42 6 24C-4 7 17-1 24 13 31-1 52 7 42 24Z',shell:'M39 38C8 54-4 21 13 9S49 9 43 30 15 43 13 25 31 9 34 22 18 32 21 23M37 38 44 44M9 14 15 18M14 8 19 14M23 5 24 12M33 7 30 13M40 12 35 17'},name={star:'별',spoon:'숟가락',crown:'왕관',fish:'물고기',key:'열쇠',umbrella:'우산',heart:'하트',shell:'조개'},tighten=([x,y,w,h])=>{const scale=.9;return[x+w*(1-scale)/2,y+h*(1-scale)/2,w*scale,h*scale]},o=(id,box)=>({id,name:name[id],shape:icon[id],box:tighten(box)});
const levels=[
 {n:1,title:'깊은 숲속 소풍',story:'토끼와 거북이의 숲속 소풍',img:'forest.png',limit:90000,items:[o('star',[.089,.057,.104,.069]),o('spoon',[.575,.051,.177,.109]),o('crown',[.305,.389,.08,.058]),o('fish',[.083,.536,.141,.05]),o('key',[.86,.331,.058,.101]),o('umbrella',[.05,.656,.165,.20]),o('heart',[.694,.664,.111,.049]),o('shell',[.823,.856,.079,.061])]},
 {n:2,title:'숨은 비 오는 서점',story:'고슴도치가 차를 내온 따뜻한 저녁',img:'bookshop.png',limit:105000,items:[o('star',[.101,.052,.07,.068]),o('spoon',[.552,.09,.055,.12]),o('crown',[.785,.725,.068,.06]),o('fish',[.054,.195,.055,.105]),o('key',[.752,.487,.07,.095]),o('umbrella',[.866,.105,.064,.22]),o('heart',[.337,.658,.07,.062]),o('shell',[.04,.645,.068,.062])]},
 {n:3,title:'달빛 옥상 미궁',story:'여우가 등불을 든 달빛 축제',img:'rooftop.png',limit:120000,items:[o('star',[.068,.06,.062,.062]),o('spoon',[.858,.094,.095,.104]),o('crown',[.108,.783,.095,.06]),o('fish',[.636,.573,.158,.058]),o('key',[.072,.288,.052,.09]),o('umbrella',[.896,.42,.088,.258]),o('heart',[.388,.618,.06,.07]),o('shell',[.784,.874,.122,.08])]}
];
const b64=v=>btoa(unescape(encodeURIComponent(JSON.stringify(v)))),unb64=v=>{try{return JSON.parse(decodeURIComponent(escape(atob(v))))}catch(_){return null}},hash=location.hash.match(/^#([cr])=(.+)$/),payload=hash&&unb64(hash[2]),challenge=hash&&hash[1]==='c'&&payload,key='gatchi_hidden_picture_v2',load=()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch(_){return{}}},save=x=>localStorage.setItem(key,JSON.stringify(x));
let mode=challenge?'duel':query.get('mode')==='online'?'duel':query.get('solo')==='1'?'solo':'landing',level=levels[Math.max(0,Math.min(2,Number((payload&&payload.l)||1)-1))],phase='ready',found=new Set(),left=0,started=0,hints=0,zoom=1,loaded=false,raf=0,hintTimer=0,down=null,duel=null;const HINT_MAX=1;
const scene=$('scene'),viewport=$('viewport'),art=$('art'),cursor={x:.5,y:.5};scene.classList.add('locked');const fmt=ms=>{const s=Math.max(0,Math.ceil(ms/1000));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},limit=()=>mode==='duel'?30000:level.limit,unlocked=n=>n<=Math.min(3,(load().max||0)+1);
function copyText(){const d=mode==='duel';$('eyebrow').textContent=d?'30 SECOND HIDDEN DUEL':'HIDDEN LITTLE THINGS · 0'+level.n;$('title').innerHTML=d?'30초 동안<span>몇 개 찾을래?</span>':'그림 속에 꼭꼭<span>숨었어요.</span>';$('intro').textContent=d?'같은 그림, 같은 30초. 찾은 개수로 친구와 겨뤄봐.':level.story+' · 제한 시간 '+fmt(level.limit);$('chapter').innerHTML=d?'친구와 숨은그림 대결<br><b>30초 · 물건 8개</b>':'Lv'+level.n+' · '+level.title+'<br><b>숨은 물건 8개</b>';$('listTitle').textContent=d?'30초 찾기 목록':'오늘의 찾기 목록';$('hint').hidden=d;$('pause').hidden=d;$('hintLabel').textContent=d?'찾은 개수':'사용한 힌트';$('gentleNote').textContent=d?'틀린 곳을 눌러도 감점은 없어요. 많이 찾는 쪽이 이겨요.':'진짜와 닮은 장식이 섞여 있어요. 힌트는 한 번뿐이에요.';$('coverEyebrow').textContent=d?'SAME PICTURE · 30 SECONDS':'Lv'+level.n+' · '+level.title;$('coverTitle').innerHTML=d?'준비됐어?<br>30초가 시작돼.':'작은 비밀을<br>찾아볼까?';$('coverDescription').innerHTML=d?'친구도 같은 그림에서 30초 동안 찾게 돼.<br>더 많이 찾은 사람이 이겨!':'닮은 장식도 섞여 있어요. 확대해서 정확한 물건을 눌러봐.'}
function levelMenu(){ $('landing').hidden=true;$('game').hidden=true;$('levelSelect').hidden=false;$('levelSelect').replaceChildren();const lead=document.createElement('p');lead.className='select-lead';lead.textContent=mode==='solo'?'1단계부터 그림 이야기를 열어봐.':'세 그림 중 아무거나 골라 30초 도전장을 만들어봐.';$('levelSelect').append(lead);levels.forEach(l=>{const lock=mode==='solo'&&!unlocked(l.n),b=document.createElement('button');b.className='level-card '+(l===level?'on':'')+(lock?' locked':'');b.disabled=lock;b.innerHTML='<span>Lv'+l.n+'</span><b>'+l.title+'</b><small>'+(mode==='duel'?'30초 · 몇 개를 찾을까?':fmt(l.limit)+' 안에 물건 8개')+'</small><i>'+(lock?'🔒 앞 단계를 먼저 완료':'이 그림으로 시작 →')+'</i>';b.onclick=()=>{level=l;levelMenu()};$('levelSelect').append(b)});const enter=document.createElement('button');enter.id='enterGame';enter.className='primary';enter.textContent=mode==='duel'?'이 그림으로 30초 대결 시작 →':'Lv'+level.n+' 시작 →';enter.onclick=openGame;$('levelSelect').append(enter)}
function openGame(){$('levelSelect').hidden=true;$('game').hidden=false;reset()}
function renderItems(){$('objects').replaceChildren();level.items.forEach(x=>{const li=document.createElement('li');li.className='object';li.id='item-'+x.id;li.innerHTML='<svg viewBox="0 0 48 48"><path d="'+x.shape+'"/></svg><span class="name">'+x.name+'</span><span class="check" hidden>✓</span>';$('objects').append(li)})}
/* 진짜 물건과 비슷하지만 정답은 아닌 장식을 얇게 겹쳐 눈으로만 가려 둔다. */
const DECOY_SPOTS=[[[.42,.14,.042,.05,-18],[.18,.33,.052,.045,12],[.72,.48,.038,.06,31],[.49,.73,.056,.042,-8],[.65,.87,.032,.055,18]],[[.42,.12,.05,.04,18],[.24,.46,.06,.04,-8],[.81,.34,.035,.06,30],[.52,.83,.045,.04,-24],[.18,.89,.03,.05,16]],[[.54,.10,.04,.04,-16],[.39,.25,.035,.06,20],[.72,.40,.03,.05,-12],[.58,.74,.045,.04,15],[.24,.94,.055,.04,-25]]];
function renderDecoys(){const spots=DECOY_SPOTS[level.n-1]||[];const ids=['star','heart','spoon','shell','key'];$('decoys').replaceChildren(...spots.map((v,i)=>{const e=document.createElement('span');e.className='decoy decoy-'+((i+level.n)%3);const [x,y,w,h,tilt]=v;e.style.cssText=`left:${x*100}%;top:${y*100}%;width:${w*100}%;height:${h*100}%;--tilt:${tilt}deg`;e.innerHTML='<svg viewBox="0 0 48 48"><path d="'+icon[ids[i]]+'"/></svg>';return e}))}
function controls(){const p=phase==='playing',z=p||phase==='complete';$('hint').disabled=!p||hints>=HINT_MAX;$('pause').disabled=!p;$('zoomIn').disabled=!z||zoom>=MAX_ZOOM-0.001;$('zoomOut').disabled=!z||zoom<=1}
const MAX_ZOOM=3;
/* 화면의 한 점(cx,cy)을 붙잡은 채 확대·축소 — 두 손가락 확대와 두 번 톡에 쓴다 */
function zoomAt(n,cx,cy){const r=viewport.getBoundingClientRect(),fx=(viewport.scrollLeft+cx-r.left)/scene.offsetWidth,fy=(viewport.scrollTop+cy-r.top)/scene.offsetHeight;
 zoom=Math.max(1,Math.min(MAX_ZOOM,n));scene.style.width=zoom*100+'%';$('zoomLabel').textContent=Math.round(zoom*100)+'%';
 viewport.scrollLeft=fx*scene.offsetWidth-(cx-r.left);viewport.scrollTop=fy*scene.offsetHeight-(cy-r.top);controls()}
function setZoom(n,a){const x=a?a.x:(viewport.scrollLeft+viewport.clientWidth/2)/scene.offsetWidth,y=a?a.y:(viewport.scrollTop+viewport.clientHeight/2)/scene.offsetHeight;zoom=Math.max(1,Math.min(MAX_ZOOM,n));scene.style.width=zoom*100+'%';$('zoomLabel').textContent=Math.round(zoom*100)+'%';viewport.scrollLeft=x*scene.offsetWidth-viewport.clientWidth/2;viewport.scrollTop=y*scene.offsetHeight-viewport.clientHeight/2;controls()}
function clearHint(){clearTimeout(hintTimer);scene.querySelector('.hint-ring')?.remove()}function mark(x,cls='mark'){const[a,b,w,h]=x.box,e=document.createElement('span');e.className=cls;Object.assign(e.style,{left:a*100+'%',top:b*100+'%',width:w*100+'%',height:h*100+'%'});$('marks').append(e)}
function foundOne(x){found.add(x.id);mark(x);clearHint();const li=$('item-'+x.id);li.classList.add('found');li.querySelector('.check').hidden=false;$('foundCount').textContent=found.size;$('progress').style.width=found.size/8*100+'%';$('message').textContent=x.name+' 발견! '+(8-found.size)+'개 남았어.';if(found.size===8)finish(true)}
function hit(x,y){if(phase!=='playing')return;const item=level.items.find(v=>x>=v.box[0]&&x<=v.box[0]+v.box[2]&&y>=v.box[1]&&y<=v.box[1]+v.box[3]);if(!item||found.has(item.id)){if(!item)$('message').textContent='아직 아니야. 목록의 모양을 다시 살펴봐!';return}foundOne(item)}
function tick(){if(phase!=='playing')return;left=limit()-(performance.now()-started);$('timer').textContent=fmt(left);if(left<=0)finish(false);else raf=requestAnimationFrame(tick)}
function start(){if(!loaded||!['ready','paused'].includes(phase))return;phase='playing';started=performance.now()-(limit()-left);$('cover').hidden=true;scene.classList.remove('locked');$('boardState').textContent=(mode==='duel'?'30초 대결 · ':'Lv'+level.n+' · ')+level.title;$('message').textContent=mode==='duel'?'시작! 30초 안에 최대한 많이 찾아봐.':'그림 속에 숨은 모양을 찾아서 눌러줘.';controls();raf=requestAnimationFrame(tick)}
function pause(){if(phase!=='playing')return;cancelAnimationFrame(raf);left-=performance.now()-started;phase='paused';clearHint();scene.classList.add('locked');$('cover').hidden=false;$('coverTitle').innerHTML='시간도<br>잠시 멈췄어.';$('coverDescription').textContent='준비되면 이어서 찾아봐.';$('start').textContent='이어서 찾기';controls()}
function finish(clear){cancelAnimationFrame(raf);phase='complete';left=Math.max(0,left-(performance.now()-started));$('timer').textContent=fmt(left);controls();$('result').hidden=false;$('nameRow').hidden=mode!=='duel';$('kakaoBtn').hidden=mode!=='duel';if(mode==='solo'){const p=load();if(clear)p.max=Math.max(p.max||0,level.n);save(p);$('resultEyebrow').textContent=clear?'LEVEL CLEAR!':'TIME UP';$('resultTitle').textContent=clear?'Lv'+level.n+' 클리어!':'이번엔 여기까지!';$('resultText').textContent=clear?fmt(level.limit-left)+' 만에 물건 8개를 다 찾았어.'+(level.n<3?' 다음 단계가 열렸어!':' 세 장의 이야기를 모두 완성했어!'):found.size+'개를 찾았어. 다음엔 더 천천히 둘러봐.';$('replay').textContent=clear&&level.n<3?'다음 단계 Lv'+(level.n+1)+' →':'같은 단계 다시 하기'}else{const me=found.size;if(challenge){duel={me,them:Number(challenge.s)||0,name:challenge.n||'친구'};const r=me>duel.them?'이겼어!':me<duel.them?'친구가 이겼어!':'무승부!';$('resultTitle').textContent=r;$('resultText').textContent='나 '+me+'개 · '+duel.name+' '+duel.them+'개. 결과를 친구에게 보내줘.';$('share').textContent='결과 링크 복사';$('kakaoBtn').textContent='💬 카톡으로 결과 보내기'}else{$('resultTitle').textContent=clear?'8개 다 찾았어!':me+'개 찾았어!';$('resultText').textContent=(clear?fmt(30000-left)+' 만에 다 찾았어. ':'')+'이제 친구도 같은 그림에서 30초 동안 찾게 해봐.';$('share').textContent='링크만 복사';$('kakaoBtn').textContent='💬 카톡으로 도전장 보내기'}
 $('nameRow').hidden=false;$('kakaoBtn').hidden=false;$('playerName').value=myName();$('replay').textContent='같은 그림 다시 하기'}$('result').scrollIntoView({behavior:'smooth',block:'nearest'})}
function reset(){cancelAnimationFrame(raf);phase='ready';found.clear();left=limit();hints=0;loaded=false;clearHint();$('marks').replaceChildren();$('result').hidden=true;$('shareMessage').textContent='';$('shareFallback').hidden=true;renderItems();renderDecoys();$('timer').textContent=fmt(limit());$('foundCount').textContent='0';$('progress').style.width='0%';$('hintCount').textContent=mode==='duel'?'0 / 8':'0 / '+HINT_MAX;$('hint').querySelector('span').textContent=HINT_MAX;$('art').src=level.img;$('art').alt=level.story+'에 숨은 물건 찾기';$('cover').hidden=false;$('start').disabled=true;$('start').textContent='그림을 불러오는 중…';$('boardState').textContent='그림을 준비하고 있어요';copyText();setZoom(1,{x:0,y:0});scene.classList.add('locked');controls()}
const NAME_KEY='gh_name';
const myName=()=>{try{return localStorage.getItem(NAME_KEY)||''}catch(_){return''}};
function duelLink(){const u=new URL(location.href);u.hash='';
 if(duel)u.hash='#r='+b64({n:duel.name,a:duel.them,b:duel.me,l:level.n});
 else u.hash='#c='+b64({n:myName()||'친구',s:found.size,l:level.n});
 return u.href}
let sdkPromise=null;
function loadKakao(){if(window.kakaoShare)return Promise.resolve();if(sdkPromise)return sdkPromise;
 sdkPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='../../assets/kakao-share.js?v=20260917-share-size';s.onload=resolve;s.onerror=()=>{sdkPromise=null;s.remove();reject(new Error('share'))};document.head.append(s)});
 return sdkPromise}
async function sendKakao(){
 const name=$('playerName').value.trim();
 if(!name){$('playerName').classList.add('need-name');$('playerName').focus();setTimeout(()=>$('playerName').classList.remove('need-name'),1600);$('shareMessage').textContent='카톡에 보일 내 이름을 먼저 적어줘.';return}
 try{localStorage.setItem(NAME_KEY,name)}catch(_){}
 const url=duelLink();
 if(['localhost','127.0.0.1'].includes(location.hostname)){$('shareMessage').textContent='미리보기에서는 링크가 내 컴퓨터에서만 열려요. 배포된 앱에서는 카톡으로 바로 보낼 수 있어요.';return}
 const img='https://noljago.co.kr/t/hidden-picture/'+level.img;
 try{
  await loadKakao();
  await window.kakaoShare({url,btn:duel?'결과 보기':'도전 받기',img,imageWidth:1122,imageHeight:1402,
   title:duel?name+'님과의 숨은그림찾기 결과 🔍':name+'님이 도전했어요 · 숨은그림찾기 🔍',
   desc:duel?'나 '+duel.me+'개 · '+duel.name+' '+duel.them+'개. 같은 그림으로 다시 겨뤄봐!':level.title+' 그림에서 30초 동안 '+found.size+'개를 찾았어. 너는 몇 개?'});
  $('shareMessage').textContent='카톡으로 보냈어!';
 }catch(e){$('shareFallback').value=url;$('shareFallback').hidden=false;$('shareFallback').select();$('shareMessage').textContent='카톡을 못 열어서 링크를 준비했어. 복사해서 보내줘.'}
}
async function share(){const u=new URL(location.href);u.hash='';let text;if(mode==='solo')text='숨은그림찾기 '+level.n+'단계, '+level.title+'을 '+fmt(level.limit-left)+' 만에 완료했어. 너도 해볼래?';else if(duel){u.hash='#r='+b64({n:duel.name,a:duel.them,b:duel.me,l:level.n});text='숨은그림찾기 결과! '+duel.name+' '+duel.them+'개 vs 나 '+duel.me+'개'}else{u.hash='#c='+b64({n:myName()||'친구',s:found.size,l:level.n});text='숨은그림찾기 '+level.title+' 30초 도전! 나는 '+found.size+'개 찾았어. 너도 몇 개 찾을래?'}if(['localhost','127.0.0.1'].includes(location.hostname)){$('shareMessage').textContent='미리보기에서는 링크가 내 컴퓨터에서만 열려요. 배포된 앱에서는 카톡으로 바로 보낼 수 있어요.';return}try{if(navigator.share)await navigator.share({title:'숨은그림찾기 · 같이놀자',text,url:u.href});else await navigator.clipboard.writeText(text+'\n'+u.href);$('shareMessage').textContent='기록과 링크를 준비했어.'}catch(e){if(e.name==='AbortError')return;$('shareFallback').value=text+'\n'+u.href;$('shareFallback').hidden=false;$('shareFallback').select();$('shareMessage').textContent='아래 내용을 복사해서 보내줘.'}}
function showResultLink(){openGame();phase='complete';duel={me:Number(payload.b)||0,them:Number(payload.a)||0,name:payload.n||'친구'};$('cover').hidden=true;const verdict=duel.me>duel.them?'내가 이겼어!':duel.me<duel.them?'친구가 이겼어!':'무승부!';$('foundCount').textContent=duel.me;$('progress').style.width=duel.me/8*100+'%';$('resultEyebrow').textContent='30 SECOND RESULT';$('resultTitle').textContent=verdict;$('resultText').textContent='나 '+duel.me+'개 · '+duel.name+' '+duel.them+'개. 같은 그림에서 30초 동안 겨뤘어.';$('replay').textContent='나도 30초 도전하기';$('share').textContent='결과 링크 공유';$('result').hidden=false;controls()}
function ready(){if(!art.naturalWidth)return;loaded=true;$('start').disabled=false;$('start').textContent='시작 →'}function failed(){$('start').textContent='그림을 불러오지 못했어요';$('coverDescription').textContent='연결을 확인한 뒤 새로고침해 주세요.'}
$('chooseSolo').onclick=()=>{mode='solo';level=levels[0];levelMenu()};$('chooseDuel').onclick=()=>{mode='duel';level=levels[0];levelMenu()};$('start').onclick=start;$('pause').onclick=pause;$('replay').onclick=()=>{if(mode==='solo'&&found.size===8&&level.n<3){level=levels[level.n];levelMenu()}else reset()};$('share').onclick=share;$('kakaoBtn').onclick=sendKakao;$('playerName').addEventListener('input',()=>$('playerName').classList.remove('need-name'));$('zoomIn').onclick=()=>setZoom(zoom+.5);$('zoomOut').onclick=()=>setZoom(zoom-.5);$('hint').onclick=()=>{if(phase!=='playing'||hints>=HINT_MAX)return;hints++;const x=level.items.find(v=>!found.has(v.id));setZoom(1.5,{x:x.box[0]+x.box[2]/2,y:x.box[1]+x.box[3]/2});mark(x,'hint-ring');hintTimer=setTimeout(clearHint,5000);$('hintCount').textContent=hints+' / '+HINT_MAX;$('hint').querySelector('span').textContent=HINT_MAX-hints;$('message').textContent='이 근처에 '+x.name+' 모양이 숨어 있어. 직접 눌러 찾아봐!';controls()};
/* 한 손가락은 밀어서 이동(브라우저 스크롤), 두 손가락은 벌려서 확대, 같은 자리 두 번 톡도 확대 */
const touches=new Map();let pinch=null,lastTap=0,lastTapPos=null;
const canZoom=()=>phase==='playing'||phase==='complete';
scene.addEventListener('pointerdown',e=>{touches.set(e.pointerId,{x:e.clientX,y:e.clientY});
 if(touches.size>1){down=null;pinch=null}
 else if(e.isPrimary)down={x:e.clientX,y:e.clientY,id:e.pointerId,left:viewport.scrollLeft,top:viewport.scrollTop}});
scene.addEventListener('pointermove',e=>{
 if(touches.has(e.pointerId))touches.set(e.pointerId,{x:e.clientX,y:e.clientY});
 if(touches.size>=2&&canZoom()){
  const[a,b]=[...touches.values()],dist=Math.hypot(a.x-b.x,a.y-b.y),mx=(a.x+b.x)/2,my=(a.y+b.y)/2;
  if(!pinch||!pinch.dist)pinch={dist,zoom};
  else zoomAt(pinch.zoom*dist/pinch.dist,mx,my);
  down=null;if(e.cancelable)e.preventDefault();return;
 }
 if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>9)down=null});
const endTouch=e=>{touches.delete(e.pointerId);if(touches.size<2)pinch=null};
scene.addEventListener('pointercancel',endTouch);
scene.addEventListener('pointerup',e=>{const many=touches.size>1;endTouch(e);
 if(!down||e.pointerId!==down.id||many)return;const d=down;down=null;
 if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>9||Math.abs(viewport.scrollLeft-d.left)+Math.abs(viewport.scrollTop-d.top)>9)return;
 const now=performance.now();
 if(canZoom()&&lastTapPos&&now-lastTap<320&&Math.hypot(e.clientX-lastTapPos.x,e.clientY-lastTapPos.y)<26){
  lastTap=0;lastTapPos=null;zoomAt(zoom>=MAX_ZOOM-0.001?1:zoom+1,e.clientX,e.clientY);return;
 }
 lastTap=now;lastTapPos={x:e.clientX,y:e.clientY};
 const r=scene.getBoundingClientRect();hit((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height)});art.addEventListener('load',ready);art.addEventListener('error',failed);document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='solo')pause()});
if(hash&&hash[1]==='r'&&payload){mode='duel';showResultLink()}else{if(mode==='landing'){$('landing').hidden=false}else levelMenu();if(challenge){$('levelSelect').hidden=true;openGame();$('message').textContent=(challenge.n||'친구')+'의 '+level.title+' 도전장이야. 30초 동안 더 많이 찾아봐!'}}
})();
